import type { Metadata } from "next";
import { Providers } from "./providers";

// Supports weights 300-900
import "@fontsource-variable/rubik";
import "./globals.css";

export const metadata: Metadata = {
  title: "Habitat Colombia | Constructora de vivienda",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
